### ISSUE TITLE
Note details preview: implement new design of note name and note content.

### ISSUE THREAD

**Issue by TomaTomoe** [DarthVanger/NeuralNotes#124] opened 2020-07-21 13:09 UTC
Implement new design of note name and note content according to template: 

![image](https://user-images.githubusercontent.com/19979138/88058582-53bca580-cb6c-11ea-87ea-b6d22864e76e.png)

**Comment by DarthVanger** [comment] 2020-07-24 16:59
Duplicate of #111

**Closed** 2020-09-13 16:46 UTC
Labels: html / styles
